apiVersion: skaffold/v4beta6
kind: Config
build:
  artifacts:
    - image: denley777/auth
      context: auth
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
      docker:
        dockerfile: Dockerfile
  local:
    push: false # disabling pushing to docker hub
manifests:
  rawYaml:
    - ./infra/k8s/*  # skaffold will watch for the changes inside this path and apply them